version: 1
update_configs:
  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
    # Apply default reviewer and label to created pull requests
    default_reviewers:
      - "ros-tooling/approvers"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
